// AUTO-GENERATED by Ardo - Do not edit manually

import { type RouteConfig, route, index } from "@react-router/dev/routes"

export default [
  index("routes/home.tsx"),
  route("guide/getting-started", "routes/guide/getting-started.mdx"),
  route("guide/markdown-features", "routes/guide/markdown-features.mdx"),
] satisfies RouteConfig
