import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"

import { prepareGeneratedDocsDirectory, resolveGeneratedDocsDirectory } from "./generator"

let routesDir: string

beforeEach(async () => {
  routesDir = await fs.mkdtemp(path.join(os.tmpdir(), "ardo-typedoc-"))
})

afterEach(async () => {
  await fs.rm(routesDir, { force: true, recursive: true })
})

describe("resolveGeneratedDocsDirectory", () => {
  it("rejects output paths that resolve to the routes directory or above it", () => {
    expect(() => resolveGeneratedDocsDirectory(routesDir, "")).toThrow("typedoc.out")
    expect(() => resolveGeneratedDocsDirectory(routesDir, ".")).toThrow("typedoc.out")
    expect(() => resolveGeneratedDocsDirectory(routesDir, "..")).toThrow("typedoc.out")
  })

  it("resolves nested generated output directories", () => {
    expect(resolveGeneratedDocsDirectory(routesDir, "api-reference")).toBe(
      path.join(routesDir, "api-reference")
    )
  })
})

describe("prepareGeneratedDocsDirectory", () => {
  it("refuses to delete a non-empty directory without the Ardo sentinel", async () => {
    const apiDirectory = path.join(routesDir, "api-reference")
    await fs.mkdir(apiDirectory)
    await fs.writeFile(path.join(apiDirectory, "handwritten.mdx"), "# Keep me\n")

    await expect(prepareGeneratedDocsDirectory(apiDirectory)).rejects.toThrow(
      "not marked as Ardo-generated"
    )
    await expect(fs.readFile(path.join(apiDirectory, "handwritten.mdx"), "utf8")).resolves.toBe(
      "# Keep me\n"
    )
  })

  it("allows an Ardo-generated directory to be replaced", async () => {
    const apiDirectory = path.join(routesDir, "api-reference")
    await fs.mkdir(apiDirectory)
    await fs.writeFile(path.join(apiDirectory, ".ardo-generated"), "Generated by Ardo.\n")
    await fs.writeFile(path.join(apiDirectory, "old.mdx"), "# Old\n")

    await prepareGeneratedDocsDirectory(apiDirectory)

    await expect(fs.access(apiDirectory)).rejects.toThrow("ENOENT")
  })
})
