import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { FileRegistry, ProjectReflection } from "typedoc"
import { afterEach, beforeEach, describe, expect, it } from "vitest"

import type { TypeDocRuntimeContext } from "./generator-config"

import { prepareGeneratedDocsDirectory, resolveGeneratedDocsDirectory } from "./generator"
import { generateIndexPage } from "./generator-pages-index"

let routesDir: string

beforeEach(async () => {
  routesDir = await fs.mkdtemp(path.join(os.tmpdir(), "ardo-typedoc-"))
})

afterEach(async () => {
  await fs.rm(routesDir, { force: true, recursive: true })
})

describe("resolveGeneratedDocsDirectory", () => {
  it("rejects output paths that resolve to the routes directory or above it", () => {
    expect(() => resolveGeneratedDocsDirectory(routesDir, "")).toThrow("typedoc.out")
    expect(() => resolveGeneratedDocsDirectory(routesDir, ".")).toThrow("typedoc.out")
    expect(() => resolveGeneratedDocsDirectory(routesDir, "..")).toThrow("typedoc.out")
  })

  it("resolves nested generated output directories", () => {
    expect(resolveGeneratedDocsDirectory(routesDir, "api-reference")).toBe(
      path.join(routesDir, "api-reference")
    )
  })
})

describe("prepareGeneratedDocsDirectory", () => {
  it("refuses to delete a non-empty directory without the Ardo sentinel", async () => {
    const apiDirectory = path.join(routesDir, "api-reference")
    await fs.mkdir(apiDirectory)
    await fs.writeFile(path.join(apiDirectory, "handwritten.mdx"), "# Keep me\n")

    await expect(prepareGeneratedDocsDirectory(apiDirectory)).rejects.toThrow(
      "not marked as Ardo-generated"
    )
    await expect(fs.readFile(path.join(apiDirectory, "handwritten.mdx"), "utf8")).resolves.toBe(
      "# Keep me\n"
    )
  })

  it("allows an Ardo-generated directory to be replaced", async () => {
    const apiDirectory = path.join(routesDir, "api-reference")
    await fs.mkdir(apiDirectory)
    await fs.writeFile(path.join(apiDirectory, ".ardo-generated"), "Generated by Ardo.\n")
    await fs.writeFile(path.join(apiDirectory, "old.mdx"), "# Old\n")

    await prepareGeneratedDocsDirectory(apiDirectory)

    await expect(fs.access(apiDirectory)).rejects.toThrow("ENOENT")
  })
})

describe("generateIndexPage", () => {
  it("does not duplicate the default API description in the body", () => {
    const doc = generateIndexPage(createTypeDocContext(), {
      componentItems: [],
      functionsByFile: new Map(),
      standaloneItems: [],
      typesByFile: new Map(),
    })

    expect(doc.frontmatter.description).toBe("Auto-generated API documentation")
    expect(doc.content).toBe("# API Reference\n")
    expect(doc.content).not.toContain("Auto-generated API documentation")
  })
})

function createTypeDocContext(): TypeDocRuntimeContext {
  return {
    basePath: "/api-reference",
    config: {
      entryPoints: ["src/index.ts"],
      excludeExternals: true,
      excludeInternal: true,
      excludePrivate: true,
      excludeProtected: false,
      markdown: {
        breadcrumbs: true,
        codeBlocks: true,
        hierarchy: true,
        sourceLinks: true,
      },
      out: "api-reference",
      sidebar: {
        collapsed: false,
        position: 100,
        title: "API Reference",
      },
      sort: ["source-order"],
    },
    packageNameCache: new Map(),
    project: new ProjectReflection("ardo", new FileRegistry()),
  }
}
