import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"

import { prepareGeneratedDocsDirectory, resolveGeneratedDocsDirectory } from "./generator"

let tempDir: string

beforeEach(async () => {
  tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "ardo-typedoc-"))
})

afterEach(async () => {
  await fs.rm(tempDir, { force: true, recursive: true })
})

describe("typedoc generator filesystem guards", () => {
  it("resolves generated docs inside the routes directory", () => {
    expect(resolveGeneratedDocsDirectory(tempDir, "api")).toBe(path.join(tempDir, "api"))
    expect(() => resolveGeneratedDocsDirectory(tempDir, ".")).toThrow(
      "typedoc.out must resolve inside the routes directory"
    )
    expect(() => resolveGeneratedDocsDirectory(tempDir, "../api")).toThrow(
      "typedoc.out must resolve inside the routes directory"
    )
  })

  it("refuses to delete handwritten content", async () => {
    const apiDir = path.join(tempDir, "api")
    await fs.mkdir(apiDir)
    await fs.writeFile(path.join(apiDir, "overview.mdx"), "# API", "utf8")

    await expect(prepareGeneratedDocsDirectory(apiDir)).rejects.toThrow("Refusing to delete")
  })

  it("clears a previously generated directory", async () => {
    const apiDir = path.join(tempDir, "api")
    await fs.mkdir(apiDir)
    await fs.writeFile(path.join(apiDir, ".ardo-generated"), "Generated by Ardo.\n", "utf8")
    await fs.writeFile(path.join(apiDir, "old.mdx"), "# Old", "utf8")

    await prepareGeneratedDocsDirectory(apiDir)

    await expect(fs.access(apiDir)).rejects.toThrow("ENOENT")
  })
})
