import fs from "node:fs/promises"
import path from "node:path"
import { readPackageUp } from "read-package-up"
import { Application, TSConfigReader, TypeDocReader } from "typedoc"

import type { GeneratedApiDoc, TypeDocConfig } from "./types"

import {
  getTypedocOptions,
  type ResolvedTypeDocConfig,
  resolveTypeDocConfig,
  type TypeDocRuntimeContext,
} from "./generator-config"
import { generateMarkdownDocs } from "./generator-docs"

const GENERATED_SENTINEL_FILE = ".ardo-generated"

export class TypeDocGenerator {
  private readonly basePath: string
  private readonly config: ResolvedTypeDocConfig
  private readonly packageNameCache = new Map<string, string | undefined>()

  constructor(config: TypeDocConfig) {
    this.config = resolveTypeDocConfig(config)
    this.basePath = `/${this.config.out}`
  }

  async generate(outputDir: string): Promise<GeneratedApiDoc[]> {
    await this.populatePackageNameCache()

    const app = await Application.bootstrapWithPlugins(getTypedocOptions(this.config), [
      new TSConfigReader(),
      new TypeDocReader(),
    ])

    const project = await app.convert()
    if (project == null) {
      throw new Error("TypeDoc conversion failed")
    }

    const context: TypeDocRuntimeContext = {
      basePath: this.basePath,
      config: this.config,
      packageNameCache: this.packageNameCache,
      project,
    }

    const docs = generateMarkdownDocs(context)
    await this.writeDocs(outputDir, docs)
    return docs
  }

  private async populatePackageNameCache(): Promise<void> {
    for (const entryPoint of this.config.entryPoints) {
      await this.resolvePackageName(entryPoint)
    }
  }

  private async resolvePackageName(filePath: string): Promise<string | undefined> {
    const directory = path.dirname(path.resolve(filePath))

    if (this.packageNameCache.has(directory)) {
      return this.packageNameCache.get(directory)
    }

    const packageResult = await readPackageUp({ cwd: directory })
    const packageName = packageResult?.packageJson.name
    const resolvedName =
      packageName == null || packageName.length === 0
        ? undefined
        : packageName.replace(/^@[^/]+\//u, "")

    this.packageNameCache.set(directory, resolvedName)
    return resolvedName
  }

  private async writeDocs(outputDir: string, docs: GeneratedApiDoc[]): Promise<void> {
    const apiDirectory = resolveGeneratedDocsDirectory(outputDir, this.config.out)
    await prepareGeneratedDocsDirectory(apiDirectory)
    await fs.mkdir(apiDirectory, { recursive: true })
    await fs.writeFile(path.join(apiDirectory, GENERATED_SENTINEL_FILE), "Generated by Ardo.\n")

    for (const doc of docs) {
      await this.writeSingleDoc(apiDirectory, doc)
    }
  }

  private async writeSingleDoc(apiDirectory: string, doc: GeneratedApiDoc): Promise<void> {
    const filePath = path.join(apiDirectory, doc.path)
    await fs.mkdir(path.dirname(filePath), { recursive: true })

    const frontmatter = createFrontmatter(doc)
    await fs.writeFile(filePath, `${frontmatter}${doc.content}`)
  }
}

function createFrontmatter(doc: GeneratedApiDoc): string {
  const lines: string[] = ["---", `title: ${doc.frontmatter.title}`]

  if (doc.frontmatter.description != null && doc.frontmatter.description.length > 0) {
    lines.push(`description: ${doc.frontmatter.description}`)
  }

  if (doc.frontmatter.sidebar_position != null) {
    lines.push(`sidebar_position: ${doc.frontmatter.sidebar_position}`)
  }

  if (doc.frontmatter.sidebar === false) {
    lines.push("sidebar: false")
  } else if (doc.frontmatter.sidebar === "leaf") {
    lines.push("sidebar: leaf")
  }

  lines.push("---", "")
  return `${lines.join("\n")}\n`
}

export function resolveGeneratedDocsDirectory(outputDir: string, out: string): string {
  const resolvedOutputDir = path.resolve(outputDir)
  const resolvedApiDirectory = path.resolve(resolvedOutputDir, out)
  const relativePath = path.relative(resolvedOutputDir, resolvedApiDirectory)

  if (relativePath === "" || relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
    throw new Error(
      `[ardo] typedoc.out must resolve inside the routes directory, not to the routes directory itself or a parent directory: ${JSON.stringify(out)}`
    )
  }

  return resolvedApiDirectory
}

export async function prepareGeneratedDocsDirectory(apiDirectory: string): Promise<void> {
  if (!(await pathExists(apiDirectory))) {
    return
  }

  if (!(await hasGeneratedSentinel(apiDirectory)) && !(await isDirectoryEmpty(apiDirectory))) {
    throw new Error(
      `[ardo] Refusing to delete ${apiDirectory} because it is not marked as Ardo-generated. Move your handwritten content elsewhere or remove the directory manually.`
    )
  }

  await fs.rm(apiDirectory, { force: true, recursive: true })
}

async function hasGeneratedSentinel(apiDirectory: string): Promise<boolean> {
  return pathExists(path.join(apiDirectory, GENERATED_SENTINEL_FILE))
}

async function isDirectoryEmpty(directory: string): Promise<boolean> {
  const entries = await fs.readdir(directory)
  return entries.length === 0
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath)
    return true
  } catch {
    return false
  }
}

export async function generateApiDocs(
  config: TypeDocConfig,
  outputDir: string
): Promise<GeneratedApiDoc[]> {
  const generator = new TypeDocGenerator(config)
  return generator.generate(outputDir)
}
