packages:
  - packages/*
  - docs
  - examples/*

overrides:
  eslint-plugin-oxlint: 1.77.0
  oxlint: 1.77.0

peerDependencyRules:
  allowedVersions:
    "eslint-plugin-jsx-a11y>eslint": "^10.0.0"

allowBuilds:
  "@swc/core": true
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - vite@8.0.16 || 8.2.1
  - "@storybook/addon-a11y@10.5.7"
  - "@storybook/addon-docs@10.5.7"
  - "@storybook/builder-vite@10.5.7"
  - "@storybook/csf-plugin@10.5.7"
  - "@storybook/react-dom-shim@10.5.7"
  - "@storybook/react-vite@10.5.7"
  - "@storybook/react@10.5.7"
  - lucide-react@1.29.0
  - storybook@10.5.7
  - "@ferriki/core@0.13.0"
  - "@ferriki/darwin-arm64@0.13.0"
  - "@ferriki/linux-arm64-gnu@0.13.0"
  - "@ferriki/linux-arm64-musl@0.13.0"
  - "@ferriki/linux-x64-gnu@0.13.0"
  - "@ferriki/linux-x64-musl@0.13.0"
  - "@ferriki/win32-arm64-msvc@0.13.0"
  - "@ferriki/win32-x64-msvc@0.13.0"
  - ferromark-darwin-arm64@3.4.0
  - ferromark-linux-arm64-gnu@3.4.0
  - ferromark-linux-arm64-musl@3.4.0
  - ferromark-linux-x64-gnu@3.4.0
  - ferromark-linux-x64-musl@3.4.0
  - ferromark-win32-arm64-msvc@3.4.0
  - ferromark-win32-x64-msvc@3.4.0
  - ferromark@3.4.0

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - unrs-resolver
