packages:
  - packages/*
  - docs
  - examples/*

overrides:
  eslint-plugin-oxlint: 1.70.0
  oxlint: 1.70.0

peerDependencyRules:
  allowedVersions:
    "eslint-plugin-jsx-a11y>eslint": "^10.0.0"

allowBuilds:
  "@swc/core": true
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - vite@8.0.16

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - unrs-resolver
