name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the motivation?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like Ardo to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of Ardo does this relate to?
      options:
        - Markdown/MDX Processing
        - Theme/UI Components
        - Configuration
        - Vite Plugin
        - Search
        - TypeDoc Integration
        - Documentation
        - CLI/Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Any examples from other tools or mockups?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
