import matter from "gray-matter"
import fs from "node:fs/promises"
import path from "node:path"

const GENERATED_SENTINEL_FILE = ".ardo-generated"

export type ContentSourceFile = {
  content: string
  filePath: string
  relativePath: string
  sourcePath: string
}

export type ContentSourceFrontmatterValue = boolean | number | string | string[] | undefined

export type ContentSourceMapping = {
  /** Markdown file or directory to materialize into the routes tree. */
  from: string
  /** Target route directory inside routesDir. */
  to: string
  /** Optional metadata synthesis hook. Values override existing/default frontmatter. */
  frontmatter?: (
    file: ContentSourceFile
  ) => Record<string, ContentSourceFrontmatterValue> | undefined
}

type ResolvedContentSourceMapping = {
  sourcePath: string
  targetPath: string
} & ContentSourceMapping

export async function materializeContentSources(input: {
  root: string
  routesDir: string
  sources: ContentSourceMapping[]
}): Promise<number> {
  let fileCount = 0
  const resolvedSources = resolveContentSources(input)

  for (const source of resolvedSources) {
    await prepareGeneratedDirectory(source.targetPath)
    await fs.mkdir(source.targetPath, { recursive: true })
    await fs.writeFile(
      path.join(source.targetPath, GENERATED_SENTINEL_FILE),
      "Generated by Ardo.\n"
    )
    fileCount += await materializeSingleSource(source)
  }

  if (fileCount > 0) {
    console.log(`[ardo] Materialized ${fileCount} content source files`)
  }

  return fileCount
}

function resolveContentSources(input: {
  root: string
  routesDir: string
  sources: ContentSourceMapping[]
}): ResolvedContentSourceMapping[] {
  return input.sources.map((source) => {
    const sourcePath = path.resolve(input.root, source.from)
    const targetPath = resolveTargetDirectory(input.routesDir, source.to)
    return { ...source, sourcePath, targetPath }
  })
}

function resolveTargetDirectory(routesDir: string, to: string): string {
  const normalizedTo = to.replaceAll("\\", "/").replace(/^\/+/u, "")
  const targetPath = path.resolve(routesDir, normalizedTo)
  const relativePath = path.relative(routesDir, targetPath)

  if (relativePath === "" || relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
    throw new Error(
      `[ardo] content.to must resolve inside the routes directory, not to the routes directory itself or a parent directory: ${JSON.stringify(to)}`
    )
  }

  return targetPath
}

async function materializeSingleSource(source: ResolvedContentSourceMapping): Promise<number> {
  const stat = await fs.stat(source.sourcePath)
  if (stat.isDirectory()) {
    return materializeSourceDirectory(source, source.sourcePath)
  }

  if (!isMarkdownFile(source.sourcePath)) {
    return 0
  }

  await materializeSourceFile({
    destinationPath: resolveIndexTargetPath(source.targetPath, source.sourcePath),
    relativePath: path.basename(source.sourcePath),
    source,
    sourcePath: source.sourcePath,
  })
  return 1
}

async function materializeSourceDirectory(
  source: ResolvedContentSourceMapping,
  directoryPath: string
): Promise<number> {
  let fileCount = 0
  const entries = await fs.readdir(directoryPath, { withFileTypes: true })

  for (const entry of entries) {
    const entryPath = path.join(directoryPath, entry.name)
    if (entry.isDirectory()) {
      fileCount += await materializeSourceDirectory(source, entryPath)
      continue
    }

    if (!entry.isFile() || !isMarkdownFile(entry.name)) {
      continue
    }

    const relativePath = path.relative(source.sourcePath, entryPath)
    await materializeSourceFile({
      destinationPath: path.join(source.targetPath, relativePath),
      relativePath,
      source,
      sourcePath: entryPath,
    })
    fileCount++
  }

  return fileCount
}

async function materializeSourceFile(input: {
  destinationPath: string
  relativePath: string
  source: ResolvedContentSourceMapping
  sourcePath: string
}): Promise<void> {
  const sourceContent = await fs.readFile(input.sourcePath, "utf8")
  const content = createMaterializedMarkdown({
    file: {
      content: sourceContent,
      filePath: input.sourcePath,
      relativePath: input.relativePath.replaceAll("\\", "/"),
      sourcePath: input.source.sourcePath,
    },
    source: input.source,
  })

  await fs.mkdir(path.dirname(input.destinationPath), { recursive: true })
  await fs.writeFile(input.destinationPath, content, "utf8")
}

function createMaterializedMarkdown(input: {
  file: ContentSourceFile
  source: ResolvedContentSourceMapping
}): string {
  const parsed = matter(input.file.content)
  const hasFrontmatter = hasYamlFrontmatter(input.file.content)
  const frontmatter = {
    ...(hasFrontmatter ? toRecord(parsed.data) : createDefaultFrontmatter(input.file)),
    ...input.source.frontmatter?.(input.file),
  }

  if (Object.keys(frontmatter).length === 0) {
    return `${parsed.content.trimStart()}\n`
  }

  return `${serializeFrontmatter(frontmatter)}${parsed.content.trimStart()}`
}

function createDefaultFrontmatter(
  file: ContentSourceFile
): Record<string, ContentSourceFrontmatterValue> {
  return {
    title: findFirstHeading(file.content) ?? formatTitleFromFileName(file.relativePath),
    order: findFilenameOrder(file.relativePath),
  }
}

function hasYamlFrontmatter(content: string): boolean {
  return content.trimStart().startsWith("---")
}

function findFirstHeading(content: string): string | undefined {
  for (const line of content.split("\n")) {
    const trimmed = line.trim()
    if (trimmed.startsWith("# ")) {
      return trimmed.slice(2).trim()
    }
  }

  return undefined
}

function findFilenameOrder(relativePath: string): number | undefined {
  const match = /^\d+/u.exec(path.basename(relativePath))
  return match == null ? undefined : Number(match[0])
}

function formatTitleFromFileName(relativePath: string): string {
  const baseName = path.basename(relativePath).replace(/\.(?:md|mdx)$/u, "")
  return baseName
    .replace(/^\d+[-_. ]*/u, "")
    .replaceAll(/[_-]/g, " ")
    .replaceAll(/\b\w/g, (character) => character.toUpperCase())
}

function serializeFrontmatter(frontmatter: Record<string, ContentSourceFrontmatterValue>): string {
  const lines = ["---"]
  for (const [key, value] of Object.entries(frontmatter)) {
    if (value === undefined) {
      continue
    }

    if (Array.isArray(value)) {
      lines.push(`${key}:`)
      for (const item of value) {
        lines.push(`  - ${JSON.stringify(item)}`)
      }
      continue
    }

    lines.push(`${key}: ${typeof value === "string" ? JSON.stringify(value) : String(value)}`)
  }

  lines.push("---", "")
  return `${lines.join("\n")}\n`
}

function toRecord(value: unknown): Record<string, ContentSourceFrontmatterValue> {
  if (typeof value !== "object" || value == null || Array.isArray(value)) {
    return {}
  }

  const record: Record<string, ContentSourceFrontmatterValue> = {}
  for (const [key, entry] of Object.entries(value)) {
    if (isFrontmatterValue(entry)) {
      record[key] = entry
    }
  }
  return record
}

function isFrontmatterValue(value: unknown): value is ContentSourceFrontmatterValue {
  return (
    value === undefined ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean" ||
    (Array.isArray(value) && value.every((entry) => typeof entry === "string"))
  )
}

function resolveIndexTargetPath(targetPath: string, sourcePath: string): string {
  const extension = path.extname(sourcePath)
  return path.join(targetPath, `index${extension}`)
}

async function prepareGeneratedDirectory(directoryPath: string): Promise<void> {
  if (!(await pathExists(directoryPath))) {
    return
  }

  if (!(await hasGeneratedSentinel(directoryPath)) && !(await isDirectoryEmpty(directoryPath))) {
    throw new Error(
      `[ardo] Refusing to delete ${directoryPath} because it is not marked as Ardo-generated. Move handwritten content elsewhere or remove the directory manually.`
    )
  }

  await fs.rm(directoryPath, { force: true, recursive: true })
}

async function hasGeneratedSentinel(directoryPath: string): Promise<boolean> {
  return pathExists(path.join(directoryPath, GENERATED_SENTINEL_FILE))
}

async function isDirectoryEmpty(directoryPath: string): Promise<boolean> {
  const entries = await fs.readdir(directoryPath)
  return entries.length === 0
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath)
    return true
  } catch {
    return false
  }
}

function isMarkdownFile(filePath: string): boolean {
  return filePath.endsWith(".md") || filePath.endsWith(".mdx")
}
