import fs from "node:fs/promises"
import path from "node:path"
import { parse } from "yaml"

import type { OpenApiConfig } from "../config/types"
import { prepareGeneratedDocsDirectory } from "../typedoc/generator"

type OpenApiDocument = {
  info?: { description?: string; title?: string; version?: string }
  openapi?: string
  paths?: Record<string, Record<string, Operation>>
}

type Operation = {
  description?: string
  operationId?: string
  parameters?: Array<{ description?: string; in?: string; name?: string; required?: boolean }>
  responses?: Record<string, { description?: string }>
  summary?: string
  tags?: string[]
}

const httpMethods = new Set(["delete", "get", "head", "options", "patch", "post", "put"])

export async function generateOpenApiDocs(input: {
  config: OpenApiConfig
  root: string
  routesDir: string
}): Promise<number> {
  const config = { out: "api", ...input.config }
  const document = await readOpenApiDocument(path.resolve(input.root, config.spec))
  if (document.openapi == null || !document.openapi.startsWith("3.")) {
    throw new Error("[ardo] openapi.spec must contain an OpenAPI 3.0 or 3.1 document.")
  }

  const outputDir = path.resolve(input.routesDir, config.out)
  await prepareGeneratedDocsDirectory(outputDir)
  await fs.mkdir(outputDir, { recursive: true })
  await fs.writeFile(path.join(outputDir, ".ardo-generated"), "Generated by Ardo.\n")
  const operations = collectOperations(document)
  await fs.writeFile(path.join(outputDir, "index.mdx"), renderIndex(document, operations), "utf8")
  for (const operation of operations) {
    const directory = path.join(outputDir, operation.tag)
    await fs.mkdir(directory, { recursive: true })
    await fs.writeFile(
      path.join(directory, `${operation.slug}.mdx`),
      renderOperation(operation),
      "utf8"
    )
  }
  return operations.length + 1
}

async function readOpenApiDocument(filePath: string): Promise<OpenApiDocument> {
  const source = await fs.readFile(filePath, "utf8")
  const value: unknown = filePath.endsWith(".json") ? JSON.parse(source) : parse(source)
  if (typeof value !== "object" || value == null || Array.isArray(value)) {
    throw new Error("[ardo] openapi.spec must contain an object document.")
  }
  return value as OpenApiDocument
}

function collectOperations(document: OpenApiDocument) {
  const operations: Array<Operation & { method: string; path: string; slug: string; tag: string }> =
    []
  for (const [routePath, pathItem] of Object.entries(document.paths ?? {})) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!httpMethods.has(method.toLowerCase())) continue
      const tag = operation.tags?.[0] ?? "endpoints"
      operations.push({
        ...operation,
        method: method.toUpperCase(),
        path: routePath,
        slug: slugify(operation.operationId ?? `${method}-${routePath}`),
        tag: slugify(tag),
      })
    }
  }
  return operations.sort((left, right) =>
    `${left.tag}/${left.slug}`.localeCompare(`${right.tag}/${right.slug}`)
  )
}

function renderIndex(
  document: OpenApiDocument,
  operations: ReturnType<typeof collectOperations>
): string {
  const title = document.info?.title ?? "API Reference"
  const groups = new Map<string, typeof operations>()
  for (const operation of operations)
    groups.set(operation.tag, [...(groups.get(operation.tag) ?? []), operation])
  return `---\ntitle: ${JSON.stringify(title)}\n---\n\n# ${title}\n\n${document.info?.description ?? ""}\n\n${[...groups].map(([tag, items]) => `## ${tag}\n\n${items.map((item) => `- [\`${item.method} ${item.path}\`](./${tag}/${item.slug})`).join("\n")}`).join("\n\n")}\n`
}

function renderOperation(operation: ReturnType<typeof collectOperations>[number]): string {
  const parameters = operation.parameters?.length
    ? `## Parameters\n\n${operation.parameters.map((parameter) => `- \`${parameter.name ?? ""}\` (${parameter.in ?? ""}${parameter.required ? ", required" : ""}): ${parameter.description ?? ""}`).join("\n")}\n`
    : ""
  const responses =
    operation.responses == null
      ? ""
      : `## Responses\n\n${Object.entries(operation.responses)
          .map(([status, response]) => `- \`${status}\`: ${response.description ?? ""}`)
          .join("\n")}\n`
  return `---\ntitle: ${JSON.stringify(`${operation.method} ${operation.path}`)}\n---\n\n# ${operation.method} ${operation.path}\n\n${operation.summary ?? operation.description ?? ""}\n\n${parameters}\n${responses}`
}

function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replaceAll(/[^a-z0-9]+/gu, "-")
      .replaceAll(/(^-|-$)/gu, "") || "endpoint"
  )
}
