import fsSync from "node:fs"
import fs from "node:fs/promises"
import path from "node:path"

export interface RouteInfo {
  /** File path relative to app directory (e.g., "routes/guide/getting-started.mdx") */
  file: string
  /** True if this is an index route */
  isIndex?: boolean
  /** URL path (e.g., "/guide/getting-started") */
  path: string
}

export function scanRoutesSync(params: { dir: string; rootDir: string }): RouteInfo[] {
  const { dir, rootDir } = params
  const routes: RouteInfo[] = []
  const entries = readDirectoryEntries(dir)

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)

    if (entry.isDirectory()) {
      routes.push(...scanRoutesSync({ dir: fullPath, rootDir }))
      continue
    }

    const route = createRouteInfo({ entryName: entry.name, fullPath, rootDir })
    if (route != null) {
      routes.push(route)
    }
  }

  return routes
}

function readDirectoryEntries(dir: string): fsSync.Dirent[] {
  try {
    return fsSync.readdirSync(dir, { withFileTypes: true })
  } catch {
    return []
  }
}

function createRouteInfo(params: {
  entryName: string
  fullPath: string
  rootDir: string
}): null | RouteInfo {
  const { entryName, fullPath, rootDir } = params
  if (!isRouteFile(entryName) || isIgnoredRouteFile(entryName)) {
    return null
  }

  const extension = getRouteExtension(entryName)
  if (extension == null) {
    return null
  }

  const relativePath = path.relative(rootDir, fullPath)
  const baseName = entryName.replace(extension, "")
  const urlPath = toRoutePath({
    baseName,
    extension,
    relativePath,
  })

  return {
    file: `routes/${relativePath.replaceAll("\\", "/")}`,
    isIndex: isIndexRoute(baseName),
    path: urlPath,
  }
}

function isRouteFile(entryName: string): boolean {
  return entryName.endsWith(".md") || entryName.endsWith(".mdx") || entryName.endsWith(".tsx")
}

function isIgnoredRouteFile(entryName: string): boolean {
  return entryName === "root.tsx" || entryName.startsWith("_")
}

function getRouteExtension(entryName: string): ".md" | ".mdx" | ".tsx" | null {
  if (entryName.endsWith(".mdx")) {
    return ".mdx"
  }

  if (entryName.endsWith(".md")) {
    return ".md"
  }

  if (entryName.endsWith(".tsx")) {
    return ".tsx"
  }

  return null
}

function toRoutePath(params: {
  baseName: string
  extension: ".md" | ".mdx" | ".tsx"
  relativePath: string
}): string {
  const { baseName, extension, relativePath } = params

  if (isIndexRoute(baseName)) {
    const parentDir = path.dirname(relativePath)
    const normalizedParent = parentDir === "." ? "" : parentDir.replaceAll("\\", "/")
    return applyDynamicSegments(`/${normalizedParent}`)
  }

  const withoutExtension = relativePath.replace(extension, "")
  return applyDynamicSegments(`/${withoutExtension.replaceAll("\\", "/")}`)
}

function isIndexRoute(baseName: string): boolean {
  return baseName === "index" || baseName === "home"
}

function applyDynamicSegments(urlPath: string): string {
  return urlPath.replaceAll(/\$(\w+)/gu, ":$1")
}

export function generateRoutesFile(routes: RouteInfo[]): string {
  const sortedRoutes = sortRoutes(routes)
  const entries = sortedRoutes.map((routeInfo) => renderRouteEntry(routeInfo))

  return `// AUTO-GENERATED by Ardo - Do not edit manually

import { type RouteConfig, route, index } from "@react-router/dev/routes"

export default [
${entries.join("\n")}
] satisfies RouteConfig
`
}

function sortRoutes(routes: RouteInfo[]): RouteInfo[] {
  return [...routes].sort((left, right) => {
    if (left.path === "/" && right.path !== "/") {
      return -1
    }

    if (right.path === "/" && left.path !== "/") {
      return 1
    }

    if (left.isIndex && !right.isIndex) {
      return -1
    }

    if (right.isIndex && !left.isIndex) {
      return 1
    }

    return left.path.localeCompare(right.path)
  })
}

function renderRouteEntry(routeInfo: RouteInfo): string {
  if (routeInfo.path === "/") {
    return `  index("${routeInfo.file}"),`
  }

  const routePath = routeInfo.path.slice(1)
  return `  route("${routePath}", "${routeInfo.file}"),`
}

export function writeRoutesFileSync(params: {
  appDir: string
  routesDir: string
  routesFilePath: string
}): void {
  const { appDir, routesDir, routesFilePath } = params
  const routes = scanRoutesSync({ dir: routesDir, rootDir: routesDir })
  if (routes.length === 0) {
    return
  }

  const content = generateRoutesFile(routes)
  const hasChanges = hasRoutesContentChangedSync(routesFilePath, content)
  if (!hasChanges) {
    return
  }

  fsSync.mkdirSync(appDir, { recursive: true })
  fsSync.writeFileSync(routesFilePath, content, "utf8")
  console.log(`[ardo] Generated routes.ts with ${routes.length} routes`)
}

function hasRoutesContentChangedSync(routesFilePath: string, nextContent: string): boolean {
  try {
    const existing = fsSync.readFileSync(routesFilePath, "utf8")
    return existing !== nextContent
  } catch {
    return true
  }
}

export async function writeRoutesFile(params: {
  appDir: string
  routesDir: string
  routesFilePath: string
}): Promise<void> {
  const { appDir, routesDir, routesFilePath } = params
  const routes = scanRoutesSync({ dir: routesDir, rootDir: routesDir })
  if (routes.length === 0) {
    return
  }

  const content = generateRoutesFile(routes)
  const hasChanges = await hasRoutesContentChanged(routesFilePath, content)
  if (!hasChanges) {
    return
  }

  await fs.mkdir(appDir, { recursive: true })
  await fs.writeFile(routesFilePath, content, "utf8")
}

async function hasRoutesContentChanged(
  routesFilePath: string,
  nextContent: string
): Promise<boolean> {
  try {
    const existing = await fs.readFile(routesFilePath, "utf8")
    return existing !== nextContent
  } catch {
    return true
  }
}
