// AUTO-GENERATED by Ardo - Do not edit manually

import { type RouteConfig, route, index } from "@react-router/dev/routes"

export default [
  index("routes/home.tsx"),
  route("api-reference/alpha", "routes/api-reference/alpha/index.md"),
  route("api-reference/alpha/functions", "routes/api-reference/alpha/functions/index.md"),
  route("api-reference/beta", "routes/api-reference/beta/index.md"),
  route("api-reference/beta/functions", "routes/api-reference/beta/functions/index.md"),
  route(
    "api-reference/beta/interfaces/repeatoptions",
    "routes/api-reference/beta/interfaces/repeatoptions.md"
  ),
  route("guide/getting-started", "routes/guide/getting-started.mdx"),
] satisfies RouteConfig
